/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pbo_database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Cika Andini
 */
public class login_frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public login_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUSER = new javax.swing.JTextField();
        btnSIGNUP = new javax.swing.JButton();
        btnLOGIN = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        txtPASSWORD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\tirai1 - Copy.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 440);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\tirai2 - Copy.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 0, 146, 440);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\logo bioskop - Copy.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 40, 80, 80);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("CINEMA XXI");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 130, 160, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\Username - Copy.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 190, 50, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\password - Copy.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 250, 50, 60);
        jPanel1.add(txtUSER);
        txtUSER.setBounds(210, 200, 180, 40);

        btnSIGNUP.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnSIGNUP.setText("SIGN UP");
        btnSIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIGNUPActionPerformed(evt);
            }
        });
        jPanel1.add(btnSIGNUP);
        btnSIGNUP.setBounds(160, 330, 90, 30);

        btnLOGIN.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnLOGIN.setText("LOGIN");
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });
        jPanel1.add(btnLOGIN);
        btnLOGIN.setBounds(290, 330, 90, 30);

        btnEXIT.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnEXIT.setText("EXIT");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        jPanel1.add(btnEXIT);
        btnEXIT.setBounds(230, 380, 80, 30);
        jPanel1.add(txtPASSWORD);
        txtPASSWORD.setBounds(210, 260, 180, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 440);

        setBounds(0, 0, 551, 466);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIGNUPActionPerformed
        String name = txtUSER.getText();
        String pass = txtPASSWORD.getText();
        if ("".equals(txtUSER.getText()) || "".equals(txtPASSWORD.getText())) {
            JOptionPane.showMessageDialog(this, "Isikan Username dan Password Dahulu!!", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        try {
            try (Statement statement = (Statement) file_koneksi.GetConnection().createStatement()) {
                statement.executeUpdate("INSERT INTO `tb_akun`(username, password) VALUES ('"+name+"', '"+pass+"')");
            }
            JOptionPane.showMessageDialog(null, "Selamat! Anda Berhasil Sign Up!");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Mohon maaf, ulangi lagi prosedur");
        }
        }
    }//GEN-LAST:event_btnSIGNUPActionPerformed

    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
        Connection connection;
        PreparedStatement ps;
        if ("".equals(txtUSER.getText()) || "".equals(txtPASSWORD.getText())) {
            JOptionPane.showMessageDialog(this, "Isikan Username dan Password Dahulu!!", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        try {
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tiket?zeroDateTimeBehavior=convertToNull", "root", "");
            ps = connection.prepareStatement("SELECT * FROM tb_akun WHERE username = ? AND password = ?");
            ps.setString(1, txtUSER.getText());
            ps.setString(2, txtPASSWORD.getText());
            ResultSet result = ps.executeQuery();
            if (result.next()) {
                new Main_Frame().show();
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Salah!");
                txtPASSWORD.setText("");
                txtUSER.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
      }
    }//GEN-LAST:event_btnLOGINActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        dispose();
    }//GEN-LAST:event_btnEXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JButton btnSIGNUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtUSER;
    // End of variables declaration//GEN-END:variables
}
