/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pbo_database;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cika Andini
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNOMOR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNAMA = new javax.swing.JTextField();
        rdFILM1 = new javax.swing.JRadioButton();
        rdFILM2 = new javax.swing.JRadioButton();
        rdFILM3 = new javax.swing.JRadioButton();
        rdFILM4 = new javax.swing.JRadioButton();
        txtJUMLAH = new javax.swing.JTextField();
        btnPESAN = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        btnBATAL = new javax.swing.JButton();
        btnEDIT = new javax.swing.JButton();
        btnREFRESH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\SAMPAH COREL\\logo bioskop - Copy.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("WELCOME TO BIOSKOP CINEMA XXI MALANG");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Jl. Danau Ranau XXI No. 18 Sawojajar Malang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 700, 100);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nomor Identitas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 150, 30);

        txtNOMOR.setBackground(new java.awt.Color(255, 204, 0));
        txtNOMOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMORActionPerformed(evt);
            }
        });
        jPanel1.add(txtNOMOR);
        txtNOMOR.setBounds(210, 140, 190, 30);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Pemesan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 150, 22);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Judul Film ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 250, 101, 22);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah tiket");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 340, 112, 22);

        txtNAMA.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.add(txtNAMA);
        txtNAMA.setBounds(210, 200, 190, 30);

        rdFILM1.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(rdFILM1);
        rdFILM1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        rdFILM1.setForeground(new java.awt.Color(255, 255, 255));
        rdFILM1.setText("Dear Nathan");
        jPanel1.add(rdFILM1);
        rdFILM1.setBounds(210, 250, 120, 27);

        rdFILM2.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(rdFILM2);
        rdFILM2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        rdFILM2.setForeground(new java.awt.Color(255, 255, 255));
        rdFILM2.setText("Harry Potter");
        jPanel1.add(rdFILM2);
        rdFILM2.setBounds(340, 250, 120, 27);

        rdFILM3.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(rdFILM3);
        rdFILM3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        rdFILM3.setForeground(new java.awt.Color(255, 255, 255));
        rdFILM3.setText("Lights Out");
        jPanel1.add(rdFILM3);
        rdFILM3.setBounds(210, 290, 120, 27);

        rdFILM4.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(rdFILM4);
        rdFILM4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        rdFILM4.setForeground(new java.awt.Color(255, 255, 255));
        rdFILM4.setText("Van Oranje");
        jPanel1.add(rdFILM4);
        rdFILM4.setBounds(340, 290, 120, 27);

        txtJUMLAH.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.add(txtJUMLAH);
        txtJUMLAH.setBounds(210, 340, 70, 30);

        btnPESAN.setBackground(new java.awt.Color(102, 102, 102));
        btnPESAN.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnPESAN.setForeground(new java.awt.Color(255, 255, 255));
        btnPESAN.setText("PESAN");
        btnPESAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPESANActionPerformed(evt);
            }
        });
        jPanel1.add(btnPESAN);
        btnPESAN.setBounds(530, 140, 140, 40);

        btnCLEAR.setBackground(new java.awt.Color(102, 102, 102));
        btnCLEAR.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnCLEAR.setForeground(new java.awt.Color(255, 255, 255));
        btnCLEAR.setText("CLEAR");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCLEAR);
        btnCLEAR.setBounds(530, 190, 140, 40);

        btnBATAL.setBackground(new java.awt.Color(102, 102, 102));
        btnBATAL.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnBATAL.setForeground(new java.awt.Color(255, 255, 255));
        btnBATAL.setText("BATALKAN");
        btnBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBATALActionPerformed(evt);
            }
        });
        jPanel1.add(btnBATAL);
        btnBATAL.setBounds(530, 240, 140, 40);

        btnEDIT.setBackground(new java.awt.Color(102, 102, 102));
        btnEDIT.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnEDIT.setForeground(new java.awt.Color(255, 255, 255));
        btnEDIT.setText("EDIT ");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });
        jPanel1.add(btnEDIT);
        btnEDIT.setBounds(530, 290, 140, 40);

        btnREFRESH.setBackground(new java.awt.Color(102, 102, 102));
        btnREFRESH.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnREFRESH.setForeground(new java.awt.Color(255, 255, 255));
        btnREFRESH.setText("REFRESH");
        btnREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREFRESHActionPerformed(evt);
            }
        });
        jPanel1.add(btnREFRESH);
        btnREFRESH.setBounds(530, 340, 140, 40);

        tb1Data.setBackground(new java.awt.Color(255, 204, 0));
        tb1Data.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        tb1Data.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Identitas", "Nama Pemesan", "Judul Film", "Jumlah tiket"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1DataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1Data);
        if (tb1Data.getColumnModel().getColumnCount() > 0) {
            tb1Data.getColumnModel().getColumn(0).setResizable(false);
            tb1Data.getColumnModel().getColumn(1).setResizable(false);
            tb1Data.getColumnModel().getColumn(2).setResizable(false);
            tb1Data.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 400, 690, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 570);

        setBounds(0, 0, 753, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNOMORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMORActionPerformed

    private void btnPESANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPESANActionPerformed
        if ("".equals(txtNOMOR.getText()) || "".equals(txtNAMA.getText()) || "".equals(txtJUMLAH.getText()) ) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else{
            String JF = "";
            if (rdFILM1.isSelected()) {
                JF = "Dear Nathan";
            }else if (rdFILM2.isSelected()) {
                JF = "Harry Potter";
            }else if (rdFILM3.isSelected()) {
                JF = "Lights Out";
            }else{
                JF = "Van Oranje";
            }
            String SQL = "INSERT INTO tb_data (NomorIdentitas,NamaPemesan,JudulFilm,JumlahTiket)"
                    + "VALUES('"+txtNOMOR.getText()+"','"+txtNAMA.getText()+"','"+JF+"','"+txtJUMLAH.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPESANActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        txtNOMOR.setText("");
        txtNAMA.setText("");
        buttonGroup1.clearSelection();
        txtJUMLAH.setText("");
    }//GEN-LAST:event_btnCLEARActionPerformed

    private void btnBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBATALActionPerformed
        int baris = tb1Data.getSelectedRow();
        if (baris != -1) {
            String NO = tb1Data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_data WHERE NomorIdentitas='"+NO+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBATALActionPerformed

    private void btnREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREFRESHActionPerformed
         selectData();
    }//GEN-LAST:event_btnREFRESHActionPerformed

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
        if ("".equals(txtNOMOR.getText()) || "".equals(txtNAMA.getText()) || 
                "".equals(txtJUMLAH.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JF = "";
            
            if (rdFILM1.isSelected()) {
                JF = "Dear Nathan";
            }else if (rdFILM2.isSelected()) {
                JF = "Harry Potter";
            }else if (rdFILM3.isSelected()) {
                JF = "Lights Out";
            }else{
                JF = "Van Oranje";
            }
            String SQL = "UPDATE tb_data SET "
                    + "NamaPemesan='"+txtNAMA.getText()+"', JudulFilm='"+JF+"', "
                    + "JumlahTiket='"+txtJUMLAH.getText()+"', "
                    + "WHERE NomorIdentitas='"+txtNOMOR.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEDITActionPerformed

    private void tb1DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1DataMouseClicked
        int baris = tb1Data.getSelectedRow();
        if (baris != -1) {
            txtNOMOR.setText(tb1Data.getValueAt(baris, 0).toString());
            txtNAMA.setText(tb1Data.getValueAt(baris, 1).toString());
            String JF = tb1Data.getValueAt(baris, 2).toString();
            if (JF.equals("Dear Nathan")) {
                rdFILM1.setSelected(true);
            } else if (JF.equals("Harry Potter")) {
                rdFILM2.setSelected(true);
            } else if (JF.equals("Lights Out")) {
                rdFILM3.setSelected(true);
            } else {
                rdFILM4.setSelected(true);
            }
            txtJUMLAH.setText(tb1Data.getValueAt(baris, 3).toString());
        }
    }//GEN-LAST:event_tb1DataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBATAL;
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnPESAN;
    private javax.swing.JButton btnREFRESH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdFILM1;
    private javax.swing.JRadioButton rdFILM2;
    private javax.swing.JRadioButton rdFILM3;
    private javax.swing.JRadioButton rdFILM4;
    private javax.swing.JTable tb1Data;
    private javax.swing.JTextField txtJUMLAH;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNOMOR;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NomorIdentitas","NamaPemesan","JudulFilm","JumlahTiket"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_data";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while (rs.next()) {
                String NomorIdentitas = rs.getString(1);
                String NamaPemesan = rs.getString(2);
                String JudulFilm = "";
                if ("Dear Nathan".equals(rs.getString(3))) {
                    JudulFilm = "Dear Nathan";
                } else if ("Harry Potter".equals(rs.getString(3))) {
                    JudulFilm = "Harry Potter";
                }else if ("Lights Out".equals(rs.getString(3))) {
                    JudulFilm = "Lights Out"; 
                }else {
                    JudulFilm = "Van Oranje";
                }
                String JumlahTiket = rs.getString(4);
                String data[] = {NomorIdentitas,NamaPemesan,JudulFilm,JumlahTiket};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb1Data.setModel(dtm);
    }
}
